### ISSUE TITLE
[refactor] Monolithic 개발 Todo List

### ISSUE THREAD

**Issue by Seotephen** [42-PINTING/BE-PINTING-monolithic#2]
# Monolithic 개발

## TODO
- [ ] ERD 설계
- [ ] (가능하다면) 클래스 설계
- [ ] (가능하다면) CI/CD 환경 구성
- [ ] DB 테이블 구성
- [ ] 명세에 따라 각 모듈별 로직 작성
- [ ] 테스트 작성(단위, 통합, 부하)
- [ ] **Realse**

> TODO: 구체화 해야합니다.

### 모듈 관련 설정

- 모듈 구성 예시: 추가되어야 할 것 또는 삭제해야할 것이 있다면 댓글로 알려주세요.
```shell
/pinting
├── board
├── member
├── comment
├── like
├── report
└── image
```
### 해결해야 하는 문제
- 1. 관리자 모듈: 관리자 기능을 분리된 모듈로 두는 방법 또는 따로 분리하지 않고 권한을 체크하는 방법 중 선택해야 합니다.
- 2. 애플리케이션 진입점(`app.java`): 개발 시에는 각 모듈마다 진입점을 두고, 배포 시에만 통합 하는 것을 추천합니다.
- `추가예정.`
